THORN-2177: Update MVC-Fraction to v1.0-PFD
thorntail/thorntail pull request #1125
Opened 2018-09-21 10:46 UTC by gtudan

Motivation
----------
Some annotations and packages were changed in the latest public final draft of MVC-Spec 1.0.

Modifications
-------------
This updates the MVC-Fraction to the latest version of the spec and it's reference implementation

Result
------
Consumers of the fractions can use the annotations and packages described in the spec. Existing
applications need to update.

- [x] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [x] [v2] Have you created a [JIRA](https://issues.jboss.org/browse/THORN) and used it in the commit message?
- [ ] [v4] Have you created a [GitHub Issue](https://github.com/thorntail/thorntail/issues) and used it in the commit message?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/thorntail/thorntail/pulls) for the same issue?
- [x] Have you built the project locally prior to submission with `mvn clean install`?

-----

2018-09-21 11:22 UTC, Ladicek submitted a review, later dismissed

2018-09-24 09:13 UTC, manovotn requested changes
@gtudan This PR causes failure of `org.wildfly.swarm.mvc.test.MvcTest` witn `NoClassDefFoundError: org/jboss/resteasy/plugins/validation/ValidatorContextResolver`.

I guess the `module.xml` misses a dependency on RE validator, e.g. `org.jboss.resteasy.resteasy-validator-provider-11`?

2018-09-24 13:57 UTC, gtudan commented
You're right, sorry about that. Should be fixed now.

2018-09-24 14:59 UTC, manovotn approved these changes

2018-09-24 15:00 UTC, merged