[THORN-2116] Mining the old 3.1.4.1 (System properties) and 4.2.2 (Datasources) sections
thorntail/thorntail pull request #1144
Opened 2018-10-10 15:37 UTC by sberyozkin

2018-10-10 15:41 UTC, sberyozkin commented
As far as https://wildfly-swarm.gitbooks.io/wildfly-swarm-users-guide/configuration_properties.html is concerned, I haven't added a dedicated 'Undertow' subsection, I guess most of the Thorntail endpoints are HTTP endpoints anyway, and I dropped few properties which I've never seen being used (the info about them is still in the linked java file)

2018-10-11 08:11 UTC, Ladicek commented
LGTM, but should wait for @tradej review :-)

2018-10-11 09:05 UTC, tradej commented
I will create a PR with suggested changes against @sberyozkin's fork.

2018-10-11 10:27 UTC, tradej requested changes
PR with suggested changes filed at https://github.com/sberyozkin/thorntail/pull/1.

2018-10-11 12:26 UTC, tradej approved these changes

2018-10-11 16:37 UTC, merged

2018-10-11 17:23 UTC, kenfinnigan commented on docs/modules/ref_commonly-used-system-properties.adoc
> +swarm.ds.name:: The name of the datasource
I'm not sure if we want to be promoting these shortcuts, as opposed to the actual DS config that is required. I say that because these settings alone aren't enough to configure a DataSource, it also needs to define the JDBC driver, etc.

2018-10-11 17:23 UTC, kenfinnigan commented on docs/modules/ref_commonly-used-system-properties.adoc
> +swarm.bind.address:: The interface to bind servers
These need to use the new "thorntail" config key