[THORN-2116] Adding the additional resources info
thorntail/thorntail pull request #1148
Opened 2018-10-12 16:39 UTC by sberyozkin

2018-10-12 16:41 UTC, sberyozkin commented
Please see https://wildfly-swarm.gitbooks.io/wildfly-swarm-users-guide/reading.html
Not sure all those links have to be included, two per each sub section should be enough, but can easily add more links

2018-10-15 07:47 UTC, Ladicek commented
I'd totally recommend including a link to the Sam Newman's book, it's really good.

2018-10-25 16:16 UTC, tradej requested changes
Small changes requested.

2018-10-25 16:16 UTC, tradej commented on docs/modules/ref_additional-resources.adoc
> +Please follow the links below to find out more about Thorntail and the Microservices Architecture
```suggestion
Follow the links below for information about Thorntail and the Microservices Architecture:
```

2018-10-25 16:16 UTC, tradej commented on docs/modules/ref_additional-resources.adoc
> +* thorntail.io[Homepage]
```suggestion
* Homepage: https://thorntail.io[thorntail.io]
```

2018-10-25 16:16 UTC, tradej commented on docs/modules/ref_additional-resources.adoc
> +* https://thorntail.io/archive/[Blog]
```suggestion
* Blog: https://thorntail.io/archive/[thorntail.io/archive]
```

2018-10-25 16:16 UTC, tradej commented on docs/modules/ref_additional-resources.adoc
> +* http://shop.oreilly.com/product/0636920033158.do[Sam Newman, "Building Microservices"]
```suggestion
* Book: http://shop.oreilly.com/product/0636920033158.do[Sam Newman, "Building Microservices"]
```

2018-10-25 16:16 UTC, tradej commented on docs/modules/ref_additional-resources.adoc
> +* https://www.manning.com/books/enterprise-java-microservices[Ken Finnigan, "Enterprise Java Microservices"]
```suggestion
* Book: https://www.manning.com/books/enterprise-java-microservices[Ken Finnigan, "Enterprise Java Microservices"]
```

2018-10-25 16:16 UTC, tradej commented on docs/modules/ref_additional-resources.adoc
> +* https://www.thoughtworks.com/de/insights/blog/microservices-nutshell[Martin Fowler, "Microservices in a Nutshell"]
```suggestion
* Blog: https://www.thoughtworks.com/de/insights/blog/microservices-nutshell[Martin Fowler, "Microservices in a Nutshell"]
```

2018-10-25 20:10 UTC, sberyozkin commented
Sheldon, thanks for the suggestions, applied

2018-10-30 11:27 UTC, sberyozkin commented
Looks ready for the merge too, can someone please approve, @Ladicek, @michalszynkiewicz

2018-10-31 10:43 UTC, Ladicek approved these changes

2018-10-31 10:45 UTC, merged