[THORN-2116] Adding a link to the Community page
thorntail/thorntail pull request #1151
Opened 2018-10-15 11:52 UTC by sberyozkin

2018-10-15 11:57 UTC, sberyozkin commented
See
https://wildfly-swarm.gitbooks.io/wildfly-swarm-users-guide/getting_involved.html

Now there is a link to the Community page with all the relevant information.

2018-10-15 12:06 UTC, Ladicek submitted a review, later dismissed

2018-10-15 14:42 UTC, sberyozkin commented
Thanks for the approval :-), I'll wait for Sheldon to give this and other PRs his writer review during the next few days (in case he'd like to change some phrases or formatting)

2018-10-15 14:54 UTC, Ladicek commented
Absolutely!

2018-10-25 16:12 UTC, tradej requested changes
Stylistic changes requested.

2018-10-25 16:12 UTC, tradej commented on docs/index.adoc
> +Community contributions are always welcome !
```suggestion
Community contributions are always welcome.
```

2018-10-25 16:12 UTC, tradej commented on docs/index.adoc
> +Please visit a https://thorntail.io/community/[Community] page to learn how to get involved.
```suggestion
For more information about how to get involved, see our https://thorntail.io/community/[Community website].
```

2018-10-25 20:11 UTC, sberyozkin commented
Thanks Sheldon :-)

2018-10-26 08:02 UTC, Ladicek approved these changes

2018-10-30 07:57 UTC, michalszynkiewicz commented
retest this please

2018-10-30 11:28 UTC, sberyozkin commented
Merging this now, given that Ladislav has approved and Sheldon's changes have been applied

2018-10-30 11:28 UTC, merged