THORN-2206: bring dependency alignment changes from product back upstream
thorntail/thorntail pull request #1161
Opened 2018-10-23 13:55 UTC by Ladicek

Motivation
----------
During the `2.2.0.Final-redhat-00021` product release, we did
a lot of dependency alignment changes. We should bring them
(or a subset of them) back upstream, to make subsequent product
releases easier.

Modifications
-------------
Port dependency alignment changes from product to upstream.

Result
------
No behavioral changes, but hopefully easier product release
next time.

- [x] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [x] [v2] Have you created a [JIRA](https://issues.jboss.org/browse/THORN) and used it in the commit message?
- [ ] [v4] Have you created a [GitHub Issue](https://github.com/thorntail/thorntail/issues) and used it in the commit message?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/thorntail/thorntail/pulls) for the same issue?
- [ ] Have you built the project locally prior to submission with `mvn clean install`?

-----

2018-10-23 14:28 UTC, sberyozkin commented
It all looks good to me though I recall starting porting some of these changes (slf4j ?) and Ken was concerned.

2018-10-23 14:31 UTC, Ladicek commented
Voicing those concerns is the exact purpose of this PR :-)

2018-10-23 16:55 UTC, kenfinnigan requested changes
As mentioned on mailing list. I don't see the long term need/benefit for this

2018-10-26 10:53 UTC, michalszynkiewicz commented on fractions/jaeger/pom.xml
> +      <exclusions>
Why is this required? opentracing-tracerresolver is another fraction, isn't it?

2018-10-26 10:54 UTC, michalszynkiewicz commented on fractions/jaeger/pom.xml
> +      <exclusions>
are we sure it will be required in the future?

2018-10-26 10:54 UTC, michalszynkiewicz commented on fractions/javaee/jaxrs-multipart/pom.xml
> +      <exclusions>
are we sure it will be required in the future?

2018-10-26 10:54 UTC, michalszynkiewicz commented on fractions/javaee/jaxrs-multipart/pom.xml
> +        <exclusion>
are we sure it will be required in the future?

2018-10-26 10:54 UTC, michalszynkiewicz commented on fractions/javaee/jaxrs/pom.xml
> +      <exclusions>
are we sure it will be required in the future?

2018-10-26 10:54 UTC, michalszynkiewicz commented on fractions/javaee/transactions/pom.xml
> +      <exclusions>
are we sure it will be required in the future?

2018-10-26 10:54 UTC, michalszynkiewicz commented on fractions/javaee/undertow/pom.xml
> +      <exclusions>
are we sure it will be required in the future?

2018-10-26 10:54 UTC, michalszynkiewicz commented on fractions/keycloak/pom.xml
> +      <exclusions>
are we sure it will be required in the future?

2018-10-26 10:55 UTC, michalszynkiewicz commented on fractions/microprofile/microprofile-config/pom.xml
> +            <exclusions>
can't it be fixed in SmallRye?

2018-10-26 10:55 UTC, michalszynkiewicz commented on fractions/microprofile/microprofile-fault-tolerance/pom.xml
> +      <exclusions>
again, it looks like something that could be fixed in SmallRye

2018-10-26 10:56 UTC, michalszynkiewicz commented on fractions/microprofile/microprofile-jwt/pom.xml
> +      <exclusions>
ditto

2018-10-26 10:56 UTC, michalszynkiewicz commented on fractions/microprofile/microprofile-openapi/pom.xml
> +        <exclusion>
again, can't we deal with it in SmallRye?

2018-10-26 11:03 UTC, michalszynkiewicz commented
Upgrading guava, bringing the archaius and hystrix related changes seems to make sense to me.

I don't understand why we would want to bring SmallRye-related changes. Will the problems with them remain in the next release?

2018-10-26 12:16 UTC, Ladicek commented
Agree that some of the problems can be fixed in SmallRye.

Re "are we sure it will be required in the future?", no, I guess we can never be sure :-) I don't have a better suggestion, though.

2018-11-26 16:41 UTC, sberyozkin commented
As far as I understand MP APIs have some OSGI alignments, and if SmallRye, at least theoretically, will be consumed by OSGI aware MP container, then it would be a prob. Have no strong opinion though...

2018-11-26 17:00 UTC, Ladicek commented
Yea that's what occurred to me as well. SmallRye probably shouldn't exclude the OSGi dependencies, that's purely Thorntail decision.

2018-12-21 12:29 UTC, juangon commented
There are conflicts in this PR now

2019-01-03 13:44 UTC, Ladicek commented
I should split some parts from this that have bigger chance of succeeding, but overall, this should be closed.

2019-01-03 13:44 UTC, closed without merging