RHOARDOC-1478
thorntail/thorntail pull request #1174
Opened 2018-11-23 10:38 UTC by inoxx03

- [ ] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [ ] [v2] Have you created a [JIRA](https://issues.jboss.org/browse/THORN) and used it in the commit message?
- [ ] [v4] Have you created a [GitHub Issue](https://github.com/thorntail/thorntail/issues) and used it in the commit message?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/thorntail/thorntail/pulls) for the same issue?
- [ ] Have you built the project locally prior to submission with `mvn clean install`?

-----

2018-11-23 11:20 UTC, manovotn commented
@tradej please take a look at this when you have a minute

ok to test

2018-11-23 11:26 UTC, Ladicek commented on docs/pom.xml
> +            <open-jdk-builder-image-name>registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift:latest</open-jdk-builder-image-name>
I don't think the variable names match :-)

2018-11-23 11:41 UTC, tradej requested changes

2018-11-23 11:41 UTC, tradej commented on docs/pom.xml
> +            <open-jdk-builder-image-name>registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift:latest</open-jdk-builder-image-name>
I agree, this was probably an oversight from @inoxx03.

2018-11-23 12:43 UTC, Ladicek approved these changes

2018-11-23 12:55 UTC, tradej approved these changes

2018-11-23 14:39 UTC, manovotn commented
Looks good, though it would be nice to have the CI passing.
@Ladicek any clue how to re-trigger Semaphore and which CI job to nudge for that linux build? Apparently it did not listen to my "ok to test" :)

2018-11-23 14:57 UTC, Ladicek commented
SemaphoreCI is only for the `4.x` branch, you can ignore it when working with 2.x.

2018-11-23 16:06 UTC, Ladicek commented
Looking at the Jenkins server, I have no idea why the Linux build wasn't triggered.

test this please

2018-11-25 17:03 UTC, manovotn commented
Tried to temper with some Jenkins settings, let's see if we still get ignored now...

2018-11-25 17:03 UTC, manovotn commented
ok to test

2018-11-26 09:24 UTC, merged