WIP: THORN-2389: Move CDI Producers code into smallrye-jwt
thorntail/thorntail pull request #1280
Opened 2019-04-30 12:54 UTC by sberyozkin

Motivation
----------
There are duplicate copies of MP JWT CDI producers in Thorntail and Quarkus, so they need to be consolidated in smallrye-jwt

Modifications
-------------
All the local CDI producers have been removed and the ones from smallrye-jwt are now being used.
Additionally, an unused ClaimLiteral class has also been removed

Result
------

CDI producers code can not be controlled in a single place, smallrye-jwt, and easily reused in Thorntail, Quarkus

2019-04-30 12:55 UTC, sberyozkin commented
At the moment it depends on smallrye-jwt 1.1.4-SNAPSHOT

2019-04-30 12:56 UTC, Ladicek requested changes
I like removing code! LGTM, but need to wait for SmallRye JWT release, that's the only change I'm requesting :-)

2019-04-30 12:57 UTC, sberyozkin commented
Sure, we will need to release smallrye-jwt 1.1.4 first

2019-05-09 14:43 UTC, Ladicek approved these changes

2019-05-10 06:58 UTC, merged