SWARM-1 - Allow packaging=jar to deploy web things.
thorntail/thorntail pull request #144
Opened 2016-09-15 19:17 UTC by bobmcwhirter

- [X] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [X] Have you created a [JIRA](https://issues.jboss.org/browse/SWARM) and used it in the commit message?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/wildfly-swarm/wildfly-swarm/pulls) for the same issue?
- [X] Have you built the project locally prior to submission with `mvn clean install`?

-----

Also, SWARM-682 and SWARM-362, which are intertwinglyly related.

Motivation
----------

For simple applications, you shouldn't have to build a .war

Modifications
-------------

Now, if :undertow or :jaxrs is present, and the default deployment
happens to be a .jar, we think that is obviously an error, and we
strongly coerce that .jar into a servlet or jaxrs war by re-arranging
the classes, adding dependencies, etc.

Additionally, the dependency between :cdi and :undertow has been
broken as it's not actually required.

Result
------

Now you can produce a normal .jar project and magically get a .war
deployed.  Only worthwhile if you're doing the default deployment.

Additionally, you can have a "pure" CDI app that doesn't involve
any web components now.

2016-09-15 20:11 UTC, kenfinnigan approved these changes
Think its good to merge when CI passes

2016-09-16 00:27 UTC, bobmcwhirter commented
Retest this please

2016-09-16 00:39 UTC, bobmcwhirter commented
If this fails again in CI can someone try it locally? I'm surprised it failed in fact.

2016-09-16 00:55 UTC, bobmcwhirter commented
Dangit. I'll review tomorrow.

2016-09-16 02:52 UTC, gastaldi commented on bootstrap/src/main/java/org/wildfly/swarm/bootstrap/env/ApplicationEnvironment.java
> +                //e.printStackTrace();
It would be nice to have a trace level logging in here

2016-09-16 02:55 UTC, gastaldi commented on undertow/src/test/java/org/wildfly/swarm/undertow/internal/DefaultWarDeploymentFactoryTest.java
> +public class DefaultWarDeploymentFactoryTest {
Is this test useful?

2016-09-16 02:57 UTC, gastaldi requested changes
The CI server failure indicates a Connection Refused error, maybe it´s worth running it again

2016-09-16 02:57 UTC, gastaldi commented
Please retest

2016-09-16 03:00 UTC, gastaldi commented
Retest this please

2016-09-16 11:32 UTC, bobmcwhirter commented
Apparently just fundamentally broken. I'll figure it out and integrate your other comments.

2016-09-16 12:55 UTC, bobmcwhirter commented
retest this please

2016-09-16 13:39 UTC, bobmcwhirter commented on bootstrap/src/main/java/org/wildfly/swarm/bootstrap/env/ApplicationEnvironment.java
> +                //e.printStackTrace();
so this is bootstrap, so prior to logging configuration mostly and it is an ignorable error, so just removing that.

2016-09-16 13:42 UTC, gastaldi approved these changes
Ok to merge if CI build passes

2016-09-16 20:21 UTC, bobmcwhirter commented
retest this please

2016-09-16 20:27 UTC, bobmcwhirter commented
retest this please

2016-09-26 13:30 UTC, kenfinnigan commented
For now we're closing this as there are issues with CI that require a reworking of how we test

2016-09-26 13:30 UTC, bobmcwhirter commented
Terrible terrible terrible.

2016-09-26 13:30 UTC, closed without merging