SWARM-1926: Adding better support for ENV varibles by
thorntail/thorntail pull request #860
Opened 2018-04-03 22:14 UTC by rareddy

1) Allowing the CAPITAL letter based properties, where they will be evaluated as lowercase keys. The values are not altered.
2) Support for escaping dash(-) and UNDERSCORE(_) in the properties. More on this below.
3) Treats any UNDERSCORE in ENV variable as dot(.) delimiter, similar to other implementations.

The escaping for dash(-) in the ENV property is achieved through _DASH_, and underscore as _UNDERSCORE_. 

For example, a swarm property like

- swarm.datasources.data-sources.DEVWF.connection-url  is represented as "SWARM_DATASOURCES_DATA_DASH_SOURCES_DEVWF_USER_DASH_NAME"

- swarm.datasources.data-sources.DEVWF.jndi_name is represented as "SWARM_DATASOURCES_DATA_DASH_SOURCES_DEVWF_JNDI_UNDERSCORE_NAME"

To do as how Spring's relaxed binding will require all the WildFly fractions to allow properties both ways or fixed in the Wildfly DMR configuration modules to allow as such, which I thought as much bigger change. The above allows a cheaper way to accomplish the same, as long as it is documented well.  I am open to alternative suggestions for escaping, this was just simple.

- [x ] Have you followed the guidelines in our [Contributing](http://wildfly-swarm.io/community/contributing/) document?
- [x ] Have you created a [JIRA](https://issues.jboss.org/browse/SWARM) and used it in the commit message?
- [x ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/wildfly-swarm/wildfly-swarm/pulls) for the same issue?
- [ x] Have you built the project locally prior to submission with `mvn clean install`?

-----

2018-04-04 12:15 UTC, kenfinnigan commented
For this to be merged we'd need documentation updated to explain how this works.

Would need to be added to `/docs/reference/configuration.adoc` I believe. @tradej is that the best place for environment variables?

2018-04-04 12:34 UTC, tradej commented
@kenfinnigan Yes, I believe this file is the best place to put this information at the moment. The file is bubbling up a little, so we may have to break it down in the future, but for the time being, it will do nicely.

2018-04-04 14:06 UTC, rareddy commented
I will update the pull request with the documentation. Any need to support list types? like

swarm.foo[1] = bar

I have never used such configuration with WildFly but I saw that in the Spring's.

2018-04-04 14:09 UTC, kenfinnigan commented
Not sure.

Any idea @bobmcwhirter ?

2018-04-04 16:34 UTC, rareddy commented
@kenfinnigan updated document per current implementation.

2018-04-04 22:11 UTC, kenfinnigan commented
retest this please

2018-04-05 11:31 UTC, tradej requested changes
Please hold the PR, I will submit a PR with doc changes to @rareddy's repo.

2018-04-05 14:02 UTC, tradej commented
Doc changes submitted at https://github.com/rareddy/wildfly-swarm/pull/1.

2018-04-11 08:23 UTC, tradej approved these changes
Docs look good.

2018-04-12 11:15 UTC, kenfinnigan approved these changes

2018-04-12 11:15 UTC, merged